"""
GitHubAgent - File operations and repository management for VIOLET-AF
UID: ALC-ROOT-1010-1111-XCOV∞
Domain: Kidhum
"""

import os
import subprocess
import json
from datetime import datetime
from typing import Dict, List, Any, Optional


class GitHubAgent:
    def __init__(self, uid="ALC-ROOT-1010-1111-XCOV∞", repo_path=None):
        self.uid = uid
        self.repo_path = repo_path or "/home/runner/work/Satan/Satan"
        self.last_operation = None
        
    def write_file(self, filepath: str, content: str, mode: str = 'w') -> Dict[str, Any]:
        """Write content to a file with UID tracking"""
        try:
            # Ensure directory exists
            os.makedirs(os.path.dirname(filepath), exist_ok=True)
            
            # Add UID header to content if it's a Python file
            if filepath.endswith('.py') and not content.startswith('"""') and '# UID:' not in content:
                uid_header = f'# UID: {self.uid}\n# Generated by VIOLET-AF Quantum Automation\n\n'
                content = uid_header + content
            
            # Write the file
            with open(filepath, mode) as f:
                f.write(content)
            
            operation_result = {
                'operation': 'write_file',
                'filepath': filepath,
                'success': True,
                'timestamp': datetime.now().isoformat(),
                'uid': self.uid,
                'file_size': len(content)
            }
            
            self.last_operation = operation_result
            return operation_result
            
        except Exception as e:
            operation_result = {
                'operation': 'write_file',
                'filepath': filepath,
                'success': False,
                'error': str(e),
                'timestamp': datetime.now().isoformat(),
                'uid': self.uid
            }
            self.last_operation = operation_result
            return operation_result
    
    def read_file(self, filepath: str) -> Dict[str, Any]:
        """Read content from a file"""
        try:
            with open(filepath, 'r') as f:
                content = f.read()
            
            operation_result = {
                'operation': 'read_file',
                'filepath': filepath,
                'success': True,
                'content': content,
                'timestamp': datetime.now().isoformat(),
                'uid': self.uid,
                'file_size': len(content)
            }
            
            self.last_operation = operation_result
            return operation_result
            
        except Exception as e:
            operation_result = {
                'operation': 'read_file',
                'filepath': filepath,
                'success': False,
                'error': str(e),
                'timestamp': datetime.now().isoformat(),
                'uid': self.uid
            }
            self.last_operation = operation_result
            return operation_result
    
    def create_directory(self, dirpath: str) -> Dict[str, Any]:
        """Create a directory structure"""
        try:
            os.makedirs(dirpath, exist_ok=True)
            
            operation_result = {
                'operation': 'create_directory',
                'dirpath': dirpath,
                'success': True,
                'timestamp': datetime.now().isoformat(),
                'uid': self.uid
            }
            
            self.last_operation = operation_result
            return operation_result
            
        except Exception as e:
            operation_result = {
                'operation': 'create_directory',
                'dirpath': dirpath,
                'success': False,
                'error': str(e),
                'timestamp': datetime.now().isoformat(),
                'uid': self.uid
            }
            self.last_operation = operation_result
            return operation_result
    
    def list_directory(self, dirpath: str = None) -> Dict[str, Any]:
        """List contents of a directory"""
        if dirpath is None:
            dirpath = self.repo_path
            
        try:
            contents = []
            for item in os.listdir(dirpath):
                item_path = os.path.join(dirpath, item)
                item_info = {
                    'name': item,
                    'path': item_path,
                    'is_file': os.path.isfile(item_path),
                    'is_directory': os.path.isdir(item_path),
                    'size': os.path.getsize(item_path) if os.path.isfile(item_path) else None
                }
                contents.append(item_info)
            
            operation_result = {
                'operation': 'list_directory',
                'dirpath': dirpath,
                'success': True,
                'contents': contents,
                'timestamp': datetime.now().isoformat(),
                'uid': self.uid
            }
            
            self.last_operation = operation_result
            return operation_result
            
        except Exception as e:
            operation_result = {
                'operation': 'list_directory',
                'dirpath': dirpath,
                'success': False,
                'error': str(e),
                'timestamp': datetime.now().isoformat(),
                'uid': self.uid
            }
            self.last_operation = operation_result
            return operation_result
    
    def git_status(self) -> Dict[str, Any]:
        """Get git status of the repository"""
        try:
            result = subprocess.run(['git', 'status', '--porcelain'], 
                                  cwd=self.repo_path, 
                                  capture_output=True, 
                                  text=True)
            
            operation_result = {
                'operation': 'git_status',
                'success': result.returncode == 0,
                'output': result.stdout,
                'error': result.stderr if result.returncode != 0 else None,
                'timestamp': datetime.now().isoformat(),
                'uid': self.uid
            }
            
            self.last_operation = operation_result
            return operation_result
            
        except Exception as e:
            operation_result = {
                'operation': 'git_status',
                'success': False,
                'error': str(e),
                'timestamp': datetime.now().isoformat(),
                'uid': self.uid
            }
            self.last_operation = operation_result
            return operation_result
    
    def git_add(self, files: List[str] = None) -> Dict[str, Any]:
        """Add files to git staging"""
        try:
            cmd = ['git', 'add']
            if files:
                cmd.extend(files)
            else:
                cmd.append('.')
                
            result = subprocess.run(cmd, 
                                  cwd=self.repo_path, 
                                  capture_output=True, 
                                  text=True)
            
            operation_result = {
                'operation': 'git_add',
                'files': files or ['.'],
                'success': result.returncode == 0,
                'output': result.stdout,
                'error': result.stderr if result.returncode != 0 else None,
                'timestamp': datetime.now().isoformat(),
                'uid': self.uid
            }
            
            self.last_operation = operation_result
            return operation_result
            
        except Exception as e:
            operation_result = {
                'operation': 'git_add',
                'files': files,
                'success': False,
                'error': str(e),
                'timestamp': datetime.now().isoformat(),
                'uid': self.uid
            }
            self.last_operation = operation_result
            return operation_result
    
    def git_commit(self, message: str) -> Dict[str, Any]:
        """Commit changes with UID-stamped message"""
        try:
            commit_message = f"[{self.uid}] {message}"
            
            result = subprocess.run(['git', 'commit', '-m', commit_message], 
                                  cwd=self.repo_path, 
                                  capture_output=True, 
                                  text=True)
            
            operation_result = {
                'operation': 'git_commit',
                'message': commit_message,
                'success': result.returncode == 0,
                'output': result.stdout,
                'error': result.stderr if result.returncode != 0 else None,
                'timestamp': datetime.now().isoformat(),
                'uid': self.uid
            }
            
            self.last_operation = operation_result
            return operation_result
            
        except Exception as e:
            operation_result = {
                'operation': 'git_commit',
                'message': message,
                'success': False,
                'error': str(e),
                'timestamp': datetime.now().isoformat(),
                'uid': self.uid
            }
            self.last_operation = operation_result
            return operation_result
    
    def commit_and_push(self, message: str, files: List[str] = None) -> Dict[str, Any]:
        """Complete git workflow: add, commit, and attempt push"""
        results = []
        
        # Add files
        add_result = self.git_add(files)
        results.append(add_result)
        
        if add_result['success']:
            # Commit changes
            commit_result = self.git_commit(message)
            results.append(commit_result)
            
            # Note: Push is disabled as per environment constraints
            # In a real environment, this would include git push
            
        operation_result = {
            'operation': 'commit_and_push',
            'message': message,
            'files': files,
            'success': all(r['success'] for r in results),
            'results': results,
            'timestamp': datetime.now().isoformat(),
            'uid': self.uid,
            'note': 'Push disabled in current environment'
        }
        
        self.last_operation = operation_result
        return operation_result
    
    def get_last_operation(self) -> Optional[Dict[str, Any]]:
        """Get the last operation performed"""
        return self.last_operation
    
    def create_quantum_file_structure(self) -> Dict[str, Any]:
        """Create the complete VIOLET-AF file structure"""
        directories = [
            os.path.join(self.repo_path, 'violet_af'),
            os.path.join(self.repo_path, 'quantum'),
            os.path.join(self.repo_path, 'webapk'),
            os.path.join(self.repo_path, 'config')
        ]
        
        results = []
        for directory in directories:
            result = self.create_directory(directory)
            results.append(result)
        
        operation_result = {
            'operation': 'create_quantum_file_structure',
            'directories': directories,
            'success': all(r['success'] for r in results),
            'results': results,
            'timestamp': datetime.now().isoformat(),
            'uid': self.uid
        }
        
        self.last_operation = operation_result
        return operation_result